### ISSUE TITLE
Checkbox selectivity doesn't show up on List rows.

### ISSUE THREAD

**Issue by ilyassloudrassi** [OfficeDev/microsoft-teams-ui-component-library#121]
### Reproduction

Code for list:
https://codesandbox.io/s/fluentui-react-teams-issue-template-forked-xitern

### Expected Behavior

When we create a List a checkbox selectivity must appear in every row.

### Actual Behavior

The list rows doesn't show any checkboxes to select any row.

**Comment by thure** [comment]
This was related to #116, which is now resolved in `alpha`. Please `npm install @fluentui/react-teams@alpha` and reopen if the bug can still be reproduced.

**Comment by ilyassloudrassi** [comment]
Unfortunately the update solved only the icons in the list component, in Wizard icons for completing the step still not showing + the steps stopped functioning activeStepIndex doesn't make any impact on the UI.

**Comment by ilyassloudrassi** [comment]
Unfortunately the update solved only the icons in the list component, in Wizard icons for completing the steps still not showing + Checkbox selectivity doesn't show up on List rows.

**Comment by ilyassloudrassi** [comment]
Update, selectivity checkbox still doesn't show up after the latest alpha version.

**Comment by thure** [comment]
Okay, can you please file a new issue with a CodeSandbox reproducing the issue? Since I can't reproduce it locally I'll need to see how you have it set up.

**Comment by thure** [comment]
I'm not able to reproduce the issue using `alpha` and correcting any TypeScript errors.

Also please bear in mind the `selectable` prop must be `true` for the List to provide selectability.

You're welcome to check my fork of your CodeSandbox here: https://codesandbox.io/embed/fluentui-react-teams-issue-template-forked-1z8kwc
